FORMAT: 1A
HOST: http://www.google.com

# JsonApiFormat
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes


## Notes Collection - case1: String `id` parameter [/case1/notes/{id*}]

A comma separated list of `id` can be passed as parameter to fetch a list of Notes. 

+ Parameters
    + id (required, string, `1,2`) ... String `id` of the Notes to perform action with. Has example value.

### Retrieves Notes [GET]
+ Response 200 (application/json)

        { 
          "notes" : [{
            "id": 1, 
            "title": "The first note in my notebook", 
            "href" : "/notes/1"
            }, {
            "id": 2, 
            "title": "The second note in my diary", 
            "href" : "/notes/2"
          }],
          "meta" : {
              "notes" : { 
                "page" : 1,
                "page_size" : 1,
                "count" : 2,
                "page_count" : 1
                }
            }
        }



## Notes Collection - case1: Number `id` parameter [/case2/notes/{id*}]

A comma separated list of `id` can be passed as parameter to fetch a list of Notes. 

+ Parameters
    + id (required, number, `1,2`) ... Numeric `id` of the Notes to perform action with. Has example value.

### Retrieves Notes [GET]
+ Response 200 (application/json)

        { 
          "notes" : [{
            "id": 3, 
            "title": "The third note in my notebook", 
            "href" : "/notes/3"
            }, {
            "id": 4, 
            "title": "The fourth note in my diary", 
            "href" : "/notes/4"
          }],
          "meta" : {
              "notes" : { 
                "page" : 1,
                "page_size" : 1,
                "count" : 2,
                "page_count" : 1
                }
            }
        }



